spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lianxi?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 178810373
    driver-class-name: com.mysql.cj.jdbc.Driver


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
